openapi: 3.0.0
info:
  title: i2nsf-api
  version: '1.0'
  description: API to deploy the i2nsf tunnel
servers:
  - url: 'http://localhost:3000'
paths:
  /i2nsf:
    post:
      summary: Create I2NSF
      operationId: api.create_i2nsf
      responses:
        '200':
          $ref: '#/components/responses/i2nsfInfo'
        '500':
          $ref: '#/components/responses/Error'
      description: Create the I2NSF IPSec tunnel
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/I2NSFRequest'
            examples:
              example-1:
                value:
                  nodes:
                    - networkInternal: 192.168.100.0/24
                      ipData: 10.0.0.161
                      ipControl: 192.168.165.101
                    - networkInternal: 192.168.200.0/24
                      ipData: 10.0.0.61
                      ipControl: 192.168.165.141
                  encAlg:
                    - des
                  intAlg:
                    - hmac-sha1-160
                  softLifetime: 120
                  hardLifetime: 140
        description: ''
      tags:
        - I2NSF
    parameters: []
  '/i2nsf/{uuid}':
    get:
      summary: I2NSF Status
      tags:
        - I2NSF
      responses:
        '200':
          $ref: '#/components/responses/i2nsfInfo'
        '400':
          $ref: '#/components/responses/Error'
      operationId: api.status_i2nsf
      description: Get the status of the depoyed I2NSF
    parameters:
      - schema:
          type: string
          format: uuid
        name: uuid
        in: path
        required: true
    delete:
      summary: ''
      operationId: api.delete_i2nsf
      responses:
        '200':
          $ref: '#/components/responses/Response'
        '404':
          $ref: '#/components/responses/Error'
        '500':
          $ref: '#/components/responses/Error'
      description: Remove I2NSF
      tags:
        - I2NSF
components:
  schemas:
    Node:
      title: Node
      type: object
      properties:
        networkInternal:
          type: string
        ipData:
          type: string
        ipControl:
          type: string
        ipDMZ:
          type: string
          format: ipv4
    I2NSFRequest:
      description: ''
      type: object
      x-examples:
        example-1:
          nodes:
            - networkInternal: 192.168.100.0/24
              ipData: 10.0.0.161
              ipControl: 192.168.165.101
            - networkInternal: 192.168.200.0/24
              ipData: 10.0.0.61
              ipControl: 192.168.165.141
          encAlg:
            - des
          intAlg:
            - hmac-sha1-160
          softLifetime: 120
          hardLifetime: 140
      properties:
        nodes:
          type: array
          items:
            $ref: '#/components/schemas/Node'
        encAlg:
          type: array
          items:
            type: string
            enum:
              - des
              - 3des
        intAlg:
          type: array
          items:
            type: string
            enum:
              - hmac-md5-96
              - hmac-md5-128
              - hmac-sha1-96
              - hmac-sha1-160
        softLifetime:
          type: number
        hardLifetime:
          type: number
      required:
        - nodes
        - encAlg
        - intAlg
  responses:
    i2nsfInfo:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                format: uuid
              nodes:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
              encAlg:
                type: string
              intAlg:
                type: string
              status:
                type: string
              softLifetime:
                type: number
              hardLifetime:
                type: number
          examples:
            example-1:
              value:
                i2nsfInfo:
                  encAlg: des
                  hardLifetime: 140
                  intAlg: hmac-sha1-160
                  nodes:
                    - ipControl: 192.168.165.141
                      ipData: 10.0.0.61
                      networkInternal: 192.168.200.0/24
                    - ipControl: 192.168.165.101
                      ipData: 10.0.0.161
                      networkInternal: 192.168.100.0/24
                  softLifetime: 120
                status: running
                uuid: d7a83420-31fc-43eb-ae86-ddf891c9261b
    Error:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                code: 500
                message: string
            properties:
              code:
                type: number
              message:
                type: string
                minLength: 1
              description:
                type: string
            required:
              - code
              - message
          examples:
            '400':
              value:
                code: 500
                message: Tunnel Not found
                description: ''
            '500':
              value:
                code: 500
                description: Node is down
                message: Internal server error
    Response:
      description: Example response
      content:
        application/json:
          schema:
            description: ''
            type: object
            x-examples:
              example-1:
                code: 500
                message: Tunnel Not found
                description: ''
            properties:
              code:
                type: number
              message:
                type: string
                minLength: 1
            required:
              - code
              - message
          examples:
            example-1:
              value:
                code: 200
                message: I2NSF Removed
  requestBodies: {}
