/*
 * i2nsf-api
 *
 * API to deploy the i2nsf tunnel
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse2001 struct {
	Code float64 `json:"code"`

	Message string `json:"message"`
}
