/*
 * i2nsf-api
 *
 * API to deploy the i2nsf tunnel
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type I2NSFConfigResponse struct {
	Id string `json:"id,omitempty"`

	Nodes []Node `json:"nodes,omitempty"`

	EncAlg string`json:"encAlg,omitempty"`

	IntAlg string `json:"intAlg,omitempty"`

	Status string `json:"status,omitempty"`

	SoftLifetime float64 `json:"softLifetime,omitempty"`

	HardLifetime float64 `json:"hardLifetime,omitempty"`
}
