/*
 * i2nsf-api
 *
 * API to deploy the i2nsf tunnel
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type I2NSFRequest struct {
	Nodes []Node `json:"nodes"`

	EncAlg []string `json:"encAlg"`

	IntAlg []string `json:"intAlg"`

	SoftLifetime LifetimeConfig `json:"softLifetime,omitempty"`

	HardLifetime LifetimeConfig `json:"hardLifetime,omitempty"`
}
