/*
 * i2nsf-api
 *
 * API to deploy the i2nsf tunnel
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Node struct {
	NetworkInternal string `json:"networkInternal,omitempty"`

	IpData string `json:"ipData,omitempty"`

	IpControl string `json:"ipControl,omitempty"`

	IpDMZ string `json:"ipDMZ,omitempty"`
}
