/*
 * i2nsf-api
 *
 * API to deploy the i2nsf tunnel
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Configuration of the lifetime values used by the tunnel
type LifetimeConfig struct {
	NBytes float64 `json:"nBytes,omitempty"`

	NPackets float64 `json:"nPackets,omitempty"`

	NTime float64 `json:"nTime,omitempty"`

	NTimeIdle float64 `json:"nTimeIdle,omitempty"`
}
