services:
  controller:
    build: ./controller
    container_name: i2nsf_controller
    networks:
      control:
          ipv4_address: 192.168.100.100
    expose:
      - "0.0.0.0:5000:5000"
  agent1:
    build: ./agent
    container_name: i2nsf_agent1
    cap_add:
      - NET_ADMIN
    networks:
      control:
        ipv4_address: 192.168.100.101
      data:
        ipv4_address: 10.0.0.101
      internal1:
        ipv4_address: 192.168.1.100
  agent2:
    build: ./agent
    container_name: i2nsf_agent2
    cap_add:
      - NET_ADMIN
    networks:
      control:
        ipv4_address: 192.168.100.102
      data:
        ipv4_address: 10.0.0.102
      internal2:
        ipv4_address: 192.168.2.100
  test1:
    build: ./internal_test
    container_name: test1
    cap_add:
      - NET_ADMIN
    networks:
      internal1:
        ipv4_address: 192.168.1.101
  test2:
    build: ./internal_test
    container_name: test2
    cap_add:
      - NET_ADMIN
    networks:
      internal2:
        ipv4_address: 192.168.2.101
networks:
  data:
    name: data
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
  internal1:
    name: internal1
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
  internal2:
    name: internal2
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
  control:
    name: control
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.100.0/24
